[package]
name = "listeria"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
regex = "^1"
lazy_static = "^1"
chrono = "^0.4"
config = "^0.10"
serde_json = "^1"
urlencoding = "^1"
roxmltree = "^0.14"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
tokio = { version = "^1", features = ["full","rt-multi-thread"] }
futures = "^0.3"
mysql_async = "^0.26"
md5 = "^0.7"
