[package]
name = "listeria"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1"
chrono = "0.4.6"
config = "0.9.2"
serde_json = "1.0.39"
urlencoding = "1.0.0"
roxmltree = "0.6.0"
#mediawiki = "0.2"
#wikibase = "0.3"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" , branch="tokio" }
#wikibase = { path='../wikibase_rs' }
tokio = { version = "^0.2", features = ["macros"] }
futures = "0.3.4"
